apiVersion: v1
kind: Service
metadata:
  name: vulcan
  namespace: vulcan
spec:
  selector:
    app: vulcan
  ports:
  - name: http
    protocol: TCP
    port: 7681
    targetPort: 7681
  - name: ssh
    protocol: TCP
    port: 8022
    targetPort: 22
  type: ClusterIP
